default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite_default: &sqlite_default
  <<: *default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *sqlite_default
  database: storage/development.sqlite3

test:
  <<: *sqlite_default
  database: storage/test.sqlite3

production:
  primary: &production_primary
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV.fetch("DATABASE_NAME", "malady_production") %>
    username: <%= ENV.fetch("DATABASE_USER", "malady") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", "5432").to_i %>
  cache:
    <<: *production_primary
    database: <%= ENV.fetch("DATABASE_NAME", "malady_production") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *production_primary
    database: <%= ENV.fetch("DATABASE_NAME", "malady_production") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *production_primary
    database: <%= ENV.fetch("DATABASE_NAME", "malady_production") %>
    migrations_paths: db/cable_migrate
